"""Build the reference sample gallery shipped with the demo.

For each of the 8 classes this writes:
    samples/<key>.npy    the raw signal in mV
    samples/<key>.png    the same signal rendered on calibrated ECG paper
    samples/<key>.json   metadata including the ground-truth label
    samples/index.json   the gallery manifest

Run:  python ml/make_samples.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "backend")]

from ml.synth import generate                                  # noqa: E402
from app.core.render import render, PaperSpec                  # noqa: E402
from app.core.taxonomy import CLASSES                          # noqa: E402

# 10 px/mm = 254 DPI. Below ~200 DPI, digitisation inflates measured QRS width;
# see docs/METHODOLOGY.md.
SPEC = PaperSpec(px_per_mm=10.0, height_mm=40.0)
FS = 360.0
DURATION = 10.0
# Seeds chosen so each strip is a canonical presentation of its class. The
# flutter seed conducts 4:1, giving clearly visible sawtooth waves between
# complexes; 2:1 flutter is a documented failure mode (docs/METHODOLOGY.md) and
# is not what a reference example should show.
SEEDS = {"normal": 7, "atrial_flutter": 1, "tachycardia": 2, "bradycardia": 1,
         "svt": 4, "afib": 6, "vfib": 5, "vpb": 0}


def main() -> int:
    out = ROOT / "samples"
    out.mkdir(exist_ok=True)
    manifest = []

    for cls in CLASSES:
        seed = SEEDS.get(cls.key, 0)
        sig, meta = generate(cls.key, duration=DURATION, fs=FS, seed=seed)
        np.save(out / f"{cls.key}.npy", sig.astype(np.float32))
        render(sig, FS, SPEC).save(out / f"{cls.key}.png", optimize=True)

        info = {
            "key": cls.key, "label": cls.key, "name": cls.name, "short": cls.short,
            "severity": cls.severity, "signature": cls.signature,
            "fs": FS, "duration_s": DURATION, "seed": seed,
            "source": "synthetic",
            "px_per_mm": SPEC.px_per_mm, "dpi": round(SPEC.px_per_mm * 25.4),
        }
        if meta.get("target_bpm"):
            info["nominal_bpm"] = round(float(meta["target_bpm"]), 1)
        (out / f"{cls.key}.json").write_text(json.dumps(info, indent=2))
        manifest.append(info)
        print(f"  {cls.key:16s} -> {cls.key}.png  ({cls.name})")

    (out / "index.json").write_text(json.dumps({
        "samples": manifest,
        "note": ("Synthetic reference strips generated by ml/synth.py. They exercise "
                 "the full pipeline offline. They are NOT clinical recordings and must "
                 "not be used to claim accuracy. See docs/METHODOLOGY.md."),
    }, indent=2))
    print(f"\nWrote {len(manifest)} samples to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
